import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { AppShell, Section } from "../components/ui";
import { getAiQualityMetrics } from "../api/items";
import { useSessionStore } from "../store/session.store";
export const AiQualityPage = () => {
    const brechoId = useSessionStore((state) => state.brechoId);
    const qualityQuery = useQuery({
        queryKey: ["ai-quality-metrics", brechoId],
        queryFn: () => getAiQualityMetrics(brechoId, { days: 30 })
    });
    return (_jsxs(AppShell, { children: [_jsx(Link, { to: "/", children: "\u2190 Voltar ao estoque" }), _jsxs("header", { children: [_jsx("h1", { style: { marginBottom: 4 }, children: "Qualidade da IA" }), _jsx("p", { style: { marginTop: 0, opacity: 0.85 }, children: "M\u00E9tricas dos \u00FAltimos 30 dias para monitorar assertividade e evolu\u00E7\u00E3o." })] }), qualityQuery.isLoading && _jsx("p", { children: "Carregando m\u00E9tricas..." }), qualityQuery.isError && _jsx("p", { children: "N\u00E3o foi poss\u00EDvel carregar m\u00E9tricas de qualidade." }), qualityQuery.data && (_jsxs(_Fragment, { children: [_jsx(Section, { title: "Vis\u00E3o geral", children: _jsxs("div", { className: "grid cols-2", children: [_jsxs("p", { style: { margin: 0 }, children: [_jsx("strong", { children: "An\u00E1lises:" }), " ", qualityQuery.data.analysesCount] }), _jsxs("p", { style: { margin: 0 }, children: [_jsx("strong", { children: "Feedbacks:" }), " ", qualityQuery.data.feedbackCount] }), _jsxs("p", { style: { margin: 0 }, children: [_jsx("strong", { children: "Per\u00EDodo:" }), " ", qualityQuery.data.periodDays, " dias"] }), _jsxs("p", { style: { margin: 0 }, children: [_jsx("strong", { children: "Desde:" }), " ", new Date(qualityQuery.data.since).toLocaleDateString("pt-BR")] })] }) }), _jsx(Section, { title: "Taxa de null por campo", children: _jsx("div", { className: "stack", style: { gap: 6 }, children: Object.entries(qualityQuery.data.nullRateByField).map(([field, info]) => (_jsxs("p", { style: { margin: 0 }, children: [_jsx("strong", { children: field }), ": ", Math.round(info.nullRate * 100), "% (", info.nullCount, "/", info.total, ")"] }, field))) }) }), _jsx(Section, { title: "Aceita\u00E7\u00E3o por campo", children: _jsx("div", { className: "stack", style: { gap: 6 }, children: Object.entries(qualityQuery.data.editAndAcceptanceByField).map(([field, info]) => (_jsxs("p", { style: { margin: 0 }, children: [_jsx("strong", { children: field }), ": aceita\u00E7\u00E3o ", Math.round(info.acceptanceRate * 100), "% \u00B7 edi\u00E7\u00E3o", " ", Math.round(info.editRate * 100), "%"] }, field))) }) }), _jsx(Section, { title: "Distribui\u00E7\u00E3o de helpfulness", children: _jsxs("p", { style: { margin: 0 }, children: ["SIM: ", qualityQuery.data.helpfulnessDistribution.SIM ?? 0, " \u00B7 PARCIAL:", " ", qualityQuery.data.helpfulnessDistribution.PARCIAL ?? 0, " \u00B7 N\u00C3O:", " ", qualityQuery.data.helpfulnessDistribution.NAO ?? 0] }) }), _jsx(Section, { title: "Top motivos", children: qualityQuery.data.topReasonCodes.length === 0 ? (_jsx("p", { style: { margin: 0, opacity: 0.8 }, children: "Sem motivos registrados no per\u00EDodo." })) : (_jsx("div", { className: "stack", style: { gap: 6 }, children: qualityQuery.data.topReasonCodes.map((reason) => (_jsxs("p", { style: { margin: 0 }, children: [_jsx("strong", { children: reason.code }), ": ", reason.count] }, reason.code))) })) })] }))] }));
};
